#ifndef WALTZVOCALAGENT_GLOBAL_H
#define WALTZVOCALAGENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WALTZVOCALAGENT_LIBRARY)
#  define WALTZVOCALAGENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define WALTZVOCALAGENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#ifndef DEFINE_SHARED_EXPORT
#define WALTZVOCALAGENT_EXPORT
#endif

#endif // WALTZVOCALAGENT_GLOBAL_H
